Introduce variables for commands so they can be overridden.

diff --git a/sbin/wifibox b/sbin/wifibox
--- a/sbin/wifibox
+++ b/sbin/wifibox
@@ -10,15 +10,33 @@ PIDFILE=${RUNDIR}/pid
 BHYVE_LOG=${LOGDIR}/bhyve.log
 GRUB_BHYVE_LOG=${LOGDIR}/grub-bhyve.log
 
+: "${BHYVE:=/usr/sbin/bhyve}"
+: "${BHYVECTL:=/usr/sbin/bhyvectl}"
+: "${DEVCTL:=/usr/sbin/devctl}"
+: "${IFCONFIG:=/sbin/ifconfig}"
+: "${SYSCTL:=/sbin/sysctl}"
+: "${DHCLIENT:=/sbin/dhclient}"
+: "${KLDLOAD:=/sbin/kldload}"
+: "${KLDUNLOAD:=/sbin/kldunload}"
+
+: "${ECHO:=/bin/echo}"
+: "${PRINTF:=/usr/bin/printf}"
+: "${SLEEP:=/bin/sleep}"
+: "${PGREP:=/bin/pgrep}"
+: "${KILL:=/bin/kill}"
+: "${RM:=/bin/rm}"
+
+: "${GRUB_BHYVE:=${LOCALBASE}/sbin/grub-bhyve}"
+
 check_virtfs() {
-    if ! (bhyve -s help | grep -Fq virtio-9p); then
-	/bin/echo "ERROR: The Virtio 9p (VirtFS) bhyve interface is not available."
+    if ! (${BHYVE} -s help | grep -Fq virtio-9p); then
+	${ECHO} "ERROR: The Virtio 9p (VirtFS) bhyve interface is not available."
 	exit 127
     fi
 }
 
 sysctl_value() {
-    /sbin/sysctl -nq "$1"
+    ${SYSCTL} -nq "$1"
 }
 
 # shellcheck disable=SC2046
@@ -26,11 +44,11 @@ check_iommu() {
     local _iommu
     local _amdvi
 
-    _iommu=$(sysctl_value "hw.vmm.iommu.enable") || /bin/echo "0"
-    _amdvi=$(sysctl_value "hw.vmm.amdvi.enable") || /bin/echo "0"
+    _iommu=$(sysctl_value "hw.vmm.iommu.enable") || ${ECHO} "0"
+    _amdvi=$(sysctl_value "hw.vmm.amdvi.enable") || ${ECHO} "0"
 
     if [ "${_iommu}" -eq "0" ] && [ "${_amdvi}" -eq "0" ]; then
-	/bin/echo "ERROR: PCI pass-through is not available for bhyve."
+	${ECHO} "ERROR: PCI pass-through is not available for bhyve."
 	exit 127
     fi
 }
@@ -39,20 +57,20 @@ check_configuration() {
     local _file="$1"
 
     if [ ! -f "${_file}" ]; then
-	/bin/echo "ERROR: ${_file} is missing, please create it from the sample."
+	${ECHO} "ERROR: ${_file} is missing, please create it from the sample."
 	exit 3
     fi
 }
 
 create_interfaces() {
-    /sbin/ifconfig bridge create name bridge-wifibox up > /dev/null
-    /sbin/ifconfig tap create name tap-wifibox > /dev/null
-    /sbin/ifconfig bridge-wifibox addm tap-wifibox > /dev/null
+    ${IFCONFIG} bridge create name bridge-wifibox up > /dev/null
+    ${IFCONFIG} tap create name tap-wifibox > /dev/null
+    ${IFCONFIG} bridge-wifibox addm tap-wifibox > /dev/null
 }
 
 destroy_interfaces() {
-    /sbin/ifconfig bridge-wifibox destroy > /dev/null
-    /sbin/ifconfig tap-wifibox destroy > /dev/null
+    ${IFCONFIG} bridge-wifibox destroy > /dev/null
+    ${IFCONFIG} tap-wifibox destroy > /dev/null
 }
 
 get_ppt_device() {
@@ -61,7 +79,7 @@ get_ppt_device() {
     # shellcheck source=./etc/bhyve.conf.sample
     . "${CONFDIR}/bhyve.conf"
 
-    echo "pci${passthru}" | sed 's!/!:!g'
+    ${ECHO} "pci${passthru}" | sed 's!/!:!g'
 }
 
 vm_start() {
@@ -73,58 +91,58 @@ vm_start() {
     # shellcheck source=./etc/bhyve.conf.sample
     . "${CONFDIR}/bhyve.conf"
 
-    /usr/sbin/devctl set driver -f "$(get_ppt_device)" ppt > /dev/null
-    ${LOCALBASE}/sbin/grub-bhyve -S -M "${memory}" -r host \
-		-m ${PREFIX}/share/wifibox/device.map \
-		-d ${PREFIX}/share/wifibox \
-		wifibox > ${GRUB_BHYVE_LOG} 2>&1
-    /usr/sbin/bhyve -c "${cpus}" -m "${memory}" -AHP -u -S \
-		    -s 0,hostbridge \
-		    -s 31,lpc \
-		    -s 4:0,virtio-blk,${PREFIX}/share/wifibox/disk.img \
-		    -s 4:1,virtio-9p,config=${CONFDIR},ro \
-		    -s 4:2,virtio-9p,var=${RUNDIR}/appliance \
-		    -s 5:0,e1000,tap-wifibox \
-		    -s 6:0,passthru,"${passthru}" \
-		    wifibox > ${BHYVE_LOG} 2>&1 &
+    ${DEVCTL} set driver -f "$(get_ppt_device)" ppt > /dev/null
+    ${GRUB_BHYVE} -S -M "${memory}" -r host \
+		  -m ${PREFIX}/share/wifibox/device.map \
+		  -d ${PREFIX}/share/wifibox \
+		  wifibox > ${GRUB_BHYVE_LOG} 2>&1
+    ${BHYVE} -c "${cpus}" -m "${memory}" -AHP -u -S \
+	     -s 0,hostbridge \
+	     -s 31,lpc \
+	     -s 4:0,virtio-blk,${PREFIX}/share/wifibox/disk.img \
+	     -s 4:1,virtio-9p,config=${CONFDIR},ro \
+	     -s 4:2,virtio-9p,var=${RUNDIR}/appliance \
+	     -s 5:0,e1000,tap-wifibox \
+	     -s 6:0,passthru,"${passthru}" \
+	     wifibox > ${BHYVE_LOG} 2>&1 &
     # Give some time for bhyve to launch.
-    /bin/sleep 1 > /dev/null
-    /bin/pgrep -fx "bhyve[: ].* wifibox" > ${PIDFILE} 2>&1
+    ${SLEEP} 1 > /dev/null
+    ${PGREP} -fx "bhyve[: ].* wifibox" > ${PIDFILE} 2>&1
 
     if [ -f "$(cat ${PIDFILE})" ]; then
 	destroy_interfaces
-	/bin/echo "ERROR: Guest could not be started, check the contents of ${BHYVE_LOG}."
+	${ECHO} "ERROR: Guest could not be started, check the contents of ${BHYVE_LOG}."
 	exit 4
     fi
 }
 
 vm_stop() {
-    /bin/kill -SIGTERM "$(cat ${PIDFILE})" > /dev/null
-    /bin/sleep 3 > /dev/null
-    /usr/sbin/bhyvectl --force-poweroff --vm=wifibox >> ${BHYVE_LOG} 2>&1
-    /usr/sbin/bhyvectl --destroy --vm=wifibox >> ${BHYVE_LOG} 2>&1
-    /bin/sleep 1 > /dev/null
-    /usr/sbin/devctl clear driver -f "$(get_ppt_device)" > /dev/null
+    ${KILL} -SIGTERM "$(cat ${PIDFILE})" > /dev/null
+    ${SLEEP} 3 > /dev/null
+    ${BHYVECTL} --force-poweroff --vm=wifibox >> ${BHYVE_LOG} 2>&1
+    ${BHYVECTL} --destroy --vm=wifibox >> ${BHYVE_LOG} 2>&1
+    ${SLEEP} 1 > /dev/null
+    ${DEVCTL} clear driver -f "$(get_ppt_device)" > /dev/null
 }
 
 assert_vm_runs() {
     if [ ! -f "${PIDFILE}" ]; then
-	/bin/echo "${PIDFILE} does not exist -- is not wifibox running?"
+	${ECHO} "${PIDFILE} does not exist -- is not wifibox running?"
 	exit 1
     fi
 }
 
 show_progress() {
-    /usr/bin/printf "."
+    ${PRINTF} "."
 }
 
 wifibox_start() {
     if [ -f "${PIDFILE}" ]; then
-	echo "${PIDFILE} already exists -- is wifibox running?"
+	${ECHO} "${PIDFILE} already exists -- is wifibox running?"
 	exit 1
     fi
 
-    /usr/bin/printf "Launching wifibox"
+    ${PRINTF} "Launching wifibox"
 
     create_interfaces
     show_progress
@@ -133,16 +151,16 @@ wifibox_start() {
     show_progress
 
     # Give some more time for the guest to boot up.
-    /bin/sleep 2 > /dev/null
-    /bin/echo "OK"
+    ${SLEEP} 2 > /dev/null
+    ${ECHO} "OK"
 
-    /sbin/dhclient bridge-wifibox
+    ${DHCLIENT} bridge-wifibox
 }
 
 wifibox_stop() {
     assert_vm_runs
 
-    /usr/bin/printf "Stopping wifibox"
+    ${PRINTF} "Stopping wifibox"
 
     vm_stop
     show_progress
@@ -150,34 +168,34 @@ wifibox_stop() {
     destroy_interfaces
     show_progress
 
-    /bin/rm ${PIDFILE} > /dev/null
-    /bin/echo "OK"
+    ${RM} ${PIDFILE} > /dev/null
+    ${ECHO} "OK"
 }
 
 # This is a workaround to recover from the unfortunate state of the
 # wireless device after resume.
 kick_vmm() {
-    if ! /sbin/kldunload vmm; then
-	/bin/echo "ERROR: Some bhyve guests are still running, vmm.ko could not be unloaded."
+    if ! ${KLDUNLOAD} vmm; then
+	${ECHO} "ERROR: Some bhyve guests are still running, vmm.ko could not be unloaded."
 	exit 127
     fi
-    /sbin/kldload vmm
+    ${KLDLOAD} vmm
 }
 
 wifibox_resume() {
     assert_vm_runs
 
-    /usr/bin/printf "Resuming wifibox"
+    ${PRINTF} "Resuming wifibox"
 
     vm_stop
     show_progress
 
-    /bin/sleep 1
+    ${SLEEP} 1
     kick_vmm
     show_progress
 
     vm_start
-    echo "OK"
+    ${ECHO} "OK"
 }
 
 wifibox_restart() {
@@ -187,9 +205,9 @@ wifibox_restart() {
 
 wifibox_status() {
     if [ -f "${PIDFILE}" ]; then
-	/bin/echo "wifibox is running as pid $(cat ${PIDFILE})."
+	${ECHO} "wifibox is running as pid $(cat ${PIDFILE})."
     else
-	/bin/echo "wifibox is not running."
+	${ECHO} "wifibox is not running."
 	return 1
     fi
 }
@@ -203,5 +221,5 @@ case "$1" in
     resume) wifibox_resume;;
     restart) wifibox_restart;;
     status) wifibox_status;;
-    *) echo "USAGE: $0 start | stop | restart | resume | status" ;;
+    *) ${ECHO} "USAGE: $0 start | stop | restart | resume | status" ;;
 esac
